import { Injectable, NotFoundException } from "@nestjs/common";
import { InjectQueue } from "@nestjs/bullmq";
import { Queue } from "bullmq";
import { DatabaseService } from "../database/database.service";
import { toPrismaTopicSlug } from "../common/topic-slug.mapper";
import { Lesson } from "@ai-tutor/db";

@Injectable()
export class LessonsService {
  constructor(
    @InjectQueue("lesson") private lessonQueue: Queue,
    private db: DatabaseService
  ) {}

  async getLesson(id: string): Promise<Lesson> {
    const lesson = await this.db.prisma.lesson.findUnique({
      where: { id },
      include: { topic: true }
    });
    if (!lesson) throw new NotFoundException("Lesson not found");
    return lesson;
  }

  async startLessonGeneration(userId: string, topicSlug: string) {
    const prismaSlug = toPrismaTopicSlug(topicSlug);
    
    // Auto-create topic if it doesn't exist to prevent 404s
    const topic = await this.db.prisma.topic.upsert({
      where: { slug: prismaSlug },
      update: {}, 
      create: {
        slug: prismaSlug,
        title: prismaSlug.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" "),
        description: "Generated by AI Tutor",
        difficulty: "intermediate",
        estimatedMinutes: 20
      }
    });

    const job = await this.lessonQueue.add("generate-lesson", {
      userId,
      topicSlug: prismaSlug,
      topicTitle: topic.title
    });

    return { jobId: job.id, status: "queued" };
  }
}
