"use client";

import { useState } from "react";
import Card from "./Card";
import SectionTitle from "./SectionTitle";
import { apiFetch } from "../lib/api";
import MarkdownContent from "./MarkdownContent";
import { unwrapApiResponse } from "../lib/unwrap";

type Lesson = { id: string; title: string; contentMarkdown: string; recap: string[]; reflectionQuestions: string[]; topicSlug: string };

export default function LessonCard({ userId, lesson, onAssignmentCreated }: {
  userId: string;
  lesson: Lesson | null;
  onAssignmentCreated: (assignmentId: string) => void;
}) {
  const [loading, setLoading] = useState(false);

  async function generateAssignment() {
    if (!lesson) return;
    setLoading(true);
    try {
      const assignment = await apiFetch<any>("/assignments", {
        method: "POST",
        body: JSON.stringify({
          userId,
          topicSlug: (lesson.topicSlug || "").replaceAll("_", "-"),
          lessonId: lesson.id
        })
      });
      const assignmentData = unwrapApiResponse<{ id: string }>(assignment);
      onAssignmentCreated(assignmentData.id);
    } finally {
      setLoading(false);
    }
  }

  return (
    <Card>
      <SectionTitle title="Lesson" subtitle="Generated by the Teacher Agent and reviewed by the Supervisor Agent." />
      {!lesson ? (
        <p className="text-slate-300">No lesson selected yet.</p>
      ) : (
        <div className="space-y-6">
          <div>
            <h3 className="text-xl font-semibold text-cyan-400">{lesson.title}</h3>
            <p className="mt-1 text-xs uppercase text-slate-400">{lesson.topicSlug}</p>
          </div>
          <MarkdownContent content={lesson.contentMarkdown} />
          <div>
            <h4 className="font-semibold">Recap</h4>
            <ul className="mt-2 list-disc pl-5 text-slate-300">
              {lesson.recap?.map((item, i) => <li key={i}>{item}</li>)}
            </ul>
          </div>
          <div>
            <h4 className="font-semibold">Reflection Questions</h4>
            <ul className="mt-2 list-disc pl-5 text-slate-300">
              {lesson.reflectionQuestions?.map((item, i) => <li key={i}>{item}</li>)}
            </ul>
          </div>
          <button onClick={generateAssignment} disabled={loading}
            className="rounded-lg bg-cyan-500 px-4 py-3 font-semibold text-black hover:bg-cyan-400 disabled:opacity-50">
            {loading ? "Generating assignment..." : "Generate Assignment"}
          </button>
        </div>
      )}
    </Card>
  );
}
