"use client";

import Card from "./Card";
import SectionTitle from "./SectionTitle";
import { apiFetch } from "../lib/api";
import { useState } from "react";
import { unwrapApiResponse } from "../lib/unwrap";

type Module = { id: string; topicSlug: string; title: string; reason: string; difficulty: string; orderIndex: number };
type Plan = { id: string; studentLevel: string; knowledgeGaps: string[]; recommendedTopics: string[]; firstLesson: string; modules: Module[] };

export default function PlanCard({ userId, plan, onLessonCreated }: {
  userId: string;
  plan: Plan | null;
  onLessonCreated: (lessonId: string) => void;
}) {
  const [loading, setLoading] = useState<string | null>(null);

  async function startLesson(topicSlug: string) {
    setLoading(topicSlug);
    try {
      const lessonRes = await apiFetch<any>("/lessons", {
        method: "POST",
        body: JSON.stringify({ userId, topicSlug })
      });
      const lesson = unwrapApiResponse<{ id: string }>(lessonRes);
      onLessonCreated(lesson.id);
    } finally {
      setLoading(null);
    }
  }

  return (
    <Card>
      <SectionTitle title="Personalized Learning Plan" subtitle="This learning path is generated by the Course Creator Agent." />
      {!plan ? (
        <p className="text-slate-300">No plan yet.</p>
      ) : (
        <div className="space-y-6">
          <div>
            <p className="text-sm text-slate-300">
              Detected level: <span className="font-bold text-cyan-400">{plan.studentLevel}</span>
            </p>
          </div>
          <div>
            <h3 className="font-semibold">Knowledge Gaps</h3>
            <ul className="mt-2 list-disc pl-5 text-slate-300">
              {plan.knowledgeGaps?.map((gap, i) => <li key={i}>{gap}</li>)}
            </ul>
          </div>
          <div>
            <h3 className="font-semibold">Modules</h3>
            <div className="mt-3 space-y-3">
              {plan.modules?.map((module) => {
                const normalizedTopic = module.topicSlug.replaceAll("_", "-");
                return (
                  <div key={module.id} className="rounded-xl border border-slate-700 p-4">
                    <div className="flex items-center justify-between gap-4">
                      <div>
                        <h4 className="font-semibold">{module.title}</h4>
                        <p className="text-sm text-slate-300">{module.reason}</p>
                      </div>
                      <div className="text-right">
                        <p className="text-xs uppercase text-cyan-400">{module.difficulty}</p>
                        <button
                          onClick={() => startLesson(normalizedTopic)}
                          disabled={loading === normalizedTopic}
                          className="mt-2 rounded-lg bg-cyan-500 px-3 py-2 text-sm font-semibold text-black disabled:opacity-50">
                          {loading === normalizedTopic ? "Loading..." : "Start Lesson"}
                        </button>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}
    </Card>
  );
}
